/** @jsxImportSource theme-ui */
import Head from "next/head";
import Script from "next/script";
import Image from "next/image";
import Navbar from "../src/components/Navbar/Navbar";
import CommunityCardList from "../src/components/CommunityCardList/CommunityCardList";
import AddCommunityForm from "../src/components/AddCommunityForm/AddCommunityForm";

import { unstable_getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]";
import type { GetServerSidePropsContext } from "next";
import type { Session } from "next-auth";
import { useState, useEffect } from "react";
import { ICommunity } from "../types/interfaces";
import { getAllCommunities } from "../src/services/communityService";

type Props = {
  user: {
    email: string;
    session: Session;
    image: string;
  };
  communities: ICommunity[];
};
export default function Home({ user, communities }: Props) {
  const [communityFormToggle, setCommunityFormToggle] = useState<boolean>(false);
  const [communityList, setCommunityList] = useState<ICommunity[]>(communities);

  return (
    <>
      <Head>
        <title>Homes Park Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script
          src="https://kit.fontawesome.com/55cdc9cb8f.js"
          crossOrigin="anonymous"
        ></script> */}
        {/* <Script
          src="https://kit.fontawesome.com/55cdc9cb8f.js"
          crossOrigin="anonymous"
        /> */}
      </Head>
      <main>
        <Navbar name={undefined} />
        {user && !communityFormToggle && (
          <div sx={{ display: "flex", justifyContent: "center" }}>
            <section
              sx={{
                variant: "containers.singlePageFormCont",
              }}
            >
              <div
                sx={{
                  display: "flex",
                  alignItems: "center",
                  width: "500px",
                  gap: "50px",
                  padding: "25px",
                }}
              >
                <span
                  sx={{
                    variant: "containers.pictureBox",
                    height: "140px",
                  }}
                >
                  <Image
                    src={user.image}
                    alt="profile pic"
                    width={140}
                    height={140}
                    sx={{ objectFit: "cover", alignSelf: "center" }}
                  />
                </span>
                <h4>{user.email}</h4>
              </div>
              <div>
                <div
                  sx={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "flex-end",
                    width: "455px",
                  }}
                >
                  <h4>My Communities:</h4>
                  <button
                    sx={{ variant: "buttons.primary" }}
                    onClick={() => setCommunityFormToggle(!communityFormToggle)}
                  >
                    Add
                  </button>
                </div>
                <CommunityCardList communityList={communityList} />
              </div>
            </section>
          </div>
        )}
        {user && communityFormToggle && (
          <AddCommunityForm
            communityFormToggle={communityFormToggle}
            setCommunityFormToggle={setCommunityFormToggle}
            communityList={communityList}
            setCommunityList={setCommunityList}
          />
        )}
      </main>
    </>
  );
}
export async function getServerSideProps(context: GetServerSidePropsContext) {
  //fetch session to validate
  const session = await unstable_getServerSession(
    context.req,
    context.res,
    authOptions
  );
  if (!session) {
    return {
      redirect: {
        destination: `api/auth/signin?callbackUrl=${process.env.REDIRECT_URL}`,
        permanent: false,
      },
    };
  }
  const { user } = session as any;
  //fetch communities
  const communities = await getAllCommunities();

  return {
    props: {
      user,
      communities
    },
  };
}
