
import Head from 'next/head'
import { useSession } from "next-auth/react"
import { Inter } from '@next/font/google'
import Navbar from '../src/components/Navbar/Navbar'
import Menu from '../src/components/Menu/Menu'
import UnitList from '../src/components/UnitList/UnitList'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // `session` will match the returned value of `callbacks.session()` from `NextAuth()`
  const { data: session } = useSession()
  console.log(session)

  return (
    <>
      <Head>
        <title>Homes Park Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/55cdc9cb8f.js" crossOrigin="anonymous"></script>
      </Head>
      <main>
        <Navbar/>
        {
          session &&
          <>
            <Menu/>
            <UnitList/>
          </>
        }
      </main>
    </>
  )
}
