export default {
  colors: {
    background: "white",
    darkGrey: "#343a40",
    lightGrey: "#f0f0f0",
    accent: "#3a5a40",
    accentLight: "#839788",
    accentLighter: "#CDD5CF",
    accentLightest: "#F0F2F0",
    accentDark: "#1D480A",

    a: "white",
    b: "#f0f0f0",
    c: "#CDD5CF",
    d: "#D6E8DB",
    e: "#C1D0B5",
    f: "#99A98F",
    text: "black",

    modes: {
      dark: {
        // background: "#343a40",
        // darkGrey: "black",
        // lightGrey: "#f0f0f0",
        // accent: "#1D480A",
        // accentLight: "#839788",
        // accentLighter: "#CDD5CF",
        // accentLightest: "#F0F2F0",
        // accentDark: "#1D480A",

        a: "#343a40",
        b: "#282b2e",
        c: "#2a3c38",
        d: "#2f4337",
        e: "#445f49",
        f: "#5c7458",
        text: "white",
      },
    },
  },
  fonts: {
    body: "Work Sans, sans-serif",
  },
  fontSizes: [12, 14, 16, 20, 24, 32, 48, 64],
  fontWeights: {
    body: 300,
    heading: 400,
    bold: 600,
  },
  space: {},
  styles: {
    root: {
      fontFamily: "body",
      fontWeight: "body",
    },
  },
  buttons: {
    primary: {
      padding: "8px",
      background: "transparent",
      border: "1px solid white",
      borderRadius: "3px",
      width: "80px",
      color: "text",
      cursor: "pointer",
      "&:hover": {
        color: "e",
        borderColor: "e",
      },
    },
    secondary: {
      padding: "10px",
      background: "accentLight",
      color: "white",
      border: "none",
      borderRadius: "3px",
      margin: "5px",
      "&:hover": {
        bg: "accent",
      },
    },
  },
  cards: {
    primary: {
      padding: "1rem",
      margin: "6px",
      borderRadius: "3px",
      border: "1px solid gray",
      backgroundColor: "background",
      height: "125px",
      width: "275px",
      minWidth: "225px",
      boxShadow: "2px 2px 2px grey",
      "&:hover": {
        bg: "accentLight",
        transform: "scale(1.02)",
        color: "white",
        opacity: "0.75",
        fontWeight: "bold",
      },
    },
    communityCard: {
      borderRadius: "10px",
      color: "a",
      minHeight: "275px",
      minWidth: "375px",
      border: "4px solid white",
      margin: "3px",
      "&:hover": {
        borderColor: "e",
      },
    },
  },
  components: {
    // menu: {
    //   position: "fixed",
    //   height: "100vh",
    //   top: "70px",
    //   bottom: "0px",
    //   left: "0px",
    //   width: "160px",
    //   margin: "8px 4px",
    //   padding: "4px",
    //   borderRadius: "4px",
    //   backgroundColor: "lightGrey",
    //   li: {
    //     fontSize: "14px",
    //     margin: "0px",
    //     alignSelf: "flex-end",
    //   },
    // },
    selectedNav: {
      border: "1px solid green",
      padding: "6px",
      borderRadius: "18px",
      "&:hover": {
        backgroundColor: "accentLight",
        color: "white",
      },
    },
    navItem: {
      border: "1px solid transparent",
      padding: "6px",
      borderRadius: "18px",
      "&:hover": {
        backgroundColor: "accentLight",
        color: "white",
      },
    },
    listItem: {
      display: "flex",
      gap: "15px",
      padding: "12px",
      color: "text",
      borderRadius: "6px",
      margin: "30px 0px",
      li: {
        fontSize: "14px",
      },
      "&:hover": {
        backgroundColor: "accentLight",
        color: "white",
      },
    },
    form: {
      display: "flex",
      flexDirection: "column",
      width: "500px",
      input: {
        padding: "10px",
        margin: "8px",
      },
      button: {
        variant: "buttons.primary",
        margin: "8px",
        width: "485px",
      },
    },
    popup: {
      display: "flex",
      flexDirection: "column",
      position: "fixed",
      bg: "accentLight",
      margin: "auto",
      top: "100px",
      left: "0px",
      right: "0px",
      borderRadius: "6px",
      zIndex: "1",
      overflow: "hidden",
      maxWidth: "700px",
      minHeight: "400px",
      padding: "10px 10px 40px",
    },
    message: {
      display: "flex",
      justifyContent: "center",
      position: "fixed",
      color: "accentLight",
      margin: "auto",
      top: "300px",
      left: "0px",
      right: "0px",
      zIndex: "1",
    },
    increaseSticker: {
      backgroundColor: "accentLighter",
      borderRadius: "3px",
      padding: "7px",
      color: "accent",
    },
  },
  containers: {
    mainPageCont: {
      display: "flex",
      flexDirection: "column",
      position: "fixed",
      top: "115px",
      height: "100vh",
      width: "100vw",
      backgroundColor: "a",
    },
    // singlePageFormCont: {
    //   display: "flex",
    //   position: "fixed",
    //   top: "60px",
    //   flexDirection: "column",
    //   alignItems: "center",
    //   width: "800px",
    //   height: "93vh",
    //   backgroundColor: "lightGrey",
    //   scroll: "none",
    // },
    unitList: {
      display: "grid",
      gridAutoFlow: "row",
      gridTemplateColumns: "repeat(auto-fill, 275px)",
      gridTemplateRows: "repeat(auto-fill, 125px)",
      gap: "20px",
      width: "90vw",
      padding: "8px 15px",
    },
    communityList: {
      display: "flex",
      alignContent: "center",
      flexDirection: "row",
      gap: "10px",
      height: "550px",
      width: "100vw",
      padding: "10px 22px",
      overflowY: "scroll",
      overflowX: "scroll",
      "&::-webkit-scrollbar": {
        display: "none",
      },
    },
    pictureBox: {
      display: "flex",
      height: "35px",
      margin: "5px",
      boxShadow: "0 5px 10px -5px rgba(0,0,0,0.5)",
      border: "2px solid white",
      borderRadius: "50%",
      aspectRatio: "1",
      overflow: "hidden",
      backgroundColor: "accent",
    },
    visuallyHidden: {
      clip: "rect(0 0 0 0)",
      clipPath: "inset(50%)",
      height: "1px",
      overflow: "hidden",
      position: "absolute",
      whiteSpace: "nowrap",
      width: "1px",
    },
    increasesBox: {
      border: "3px solid gray",
      borderRadius: "6px",
      backgroundColor: "accentLightest",
      zIndex: "1px",
      margin: "15px",
      padding: "5px",
      paddingBottom: "8px",
      display: "flex",
      gap: "10px",
      flexDirection: "column",
    },
  },
};
