export default {
  colors: {
    background: "white",
    darkGrey: "#343a40",
    lightGrey: "#f0f0f0",
    accent: "#3a5a40",
    accentLight: "#839788",
    accentDark: "#1D480A",
    champagne: "#EEE0CB",
    modes: {
      dark: {
        text: "#fff",
        background: "#000",
        accent: "#0cf",
      },
    },
  },
  fonts: {
    body: "Work Sans, sans-serif",
  },
  fontSizes: [12, 14, 16, 20, 24, 32, 48, 64],
  fontWeights: {
    body: 300,
    heading: 400,
    bold: 600,
  },
  space: {},
  styles: {
    root: {
      fontFamily: "body",
      fontWeight: "body",
    },
  },
  buttons: {
    primary: {
      padding: "10px",
      background: "transparent",
      border: "1px solid black",
      borderRadius: "3px",
      width: "80px",
      cursor: "pointer",
      boxShadow: "2px 2px 2px grey",
      "&:hover": {
        color: "black",
      },
      "&:active": {
        color: "black",
        boxShadow: "none",
      },
    },
    secondary: {
      padding: "10px",
      background: "accentLight",
      color: "white",
      border: "none",
      borderRadius: "3px",
      margin: "5px",
      "&:hover": {
        bg: "accent",
      },
    },
  },
  cards: {
    primary: {
      padding: "1rem",
      margin: "6px",
      borderRadius: "3px",
      border: "1px solid green",
      height: "125px",
      width: "275px",
      minWidth: "225px",
      boxShadow: "2px 2px 2px grey",
      "&:hover": {
        bg: "accentLight",
        transform: "scale(1.02)",
        color: "white",
        opacity: "0.75",
        fontWeight: "bold"
      },
    },
    communityCard: {
      padding: "1rem",
      borderRadius: "6px",
      background: "accent",
      color: "white",
      minHeight: "200px",
      width: "455px",
      minWidth: "300px",
      display: "flex",
      flexDirection: "column",
      alignSelf: "flex-start",
      justifyContent: "flex-end",
      "&:hover": {
        bg: "text",
        opacity: "0.90",
        transform: "scale(1.02)",
      },
    },
  },
  components: {
    menu: {
      position: "fixed",
      height: "100vh",
      top: "70px",
      bottom: "0px",
      left: "0px",
      width: "155px",
      margin: "8px 4px",
      padding: "8px",
      borderRadius: "4px",
      //border: "1px solid green",
      backgroundColor: "lightGrey",
      li: {
        fontSize: "13px",
        margin: "0px",
        alignSelf: "flex-end",
      },
    },
    listItem: {
      display: "flex",
      gap: "15px",
      padding: "0px 0px 25px",
      color: "text",
      li: {
        fontSize: "14px",
      },
    },
    form: {
      display: "flex",
      flexDirection: "column",
      width: "500px",
      input: {
        padding: "10px",
        margin: "8px",
      },
      button: {
        variant: "buttons.primary",
        margin: "8px",
        width: "485px",
      },
    },
    popup: {
      display: "flex",
        justifyContent: "center",
        position: "fixed",
        bg: "accentLight",
        margin: "auto",
        top: "100px",
        left: "0px",
        right: "0px",
        borderRadius: "6px",
        zIndex: "1",
        maxWidth: "600px",
        maxHeight: "400px",
        width: "800px",
        height: "93vh",
    }
  },
  containers: {
    mainPageCont: {
      display: "flex",
      position: "absolute",
      top: "70px",
      height: "100vh",
      width: "100vw",
    },
    singlePageFormCont: {
      display: "flex",
      position: "fixed",
      top: "60px",
      flexDirection: "column",
      alignItems: "center",
      width: "800px",
      height: "93vh",
      backgroundColor: "lightGrey",
      scroll: "none",
    },
    unitList: {
      display: "grid",
      gridAutoFlow: "row",
      gridTemplateColumns: "repeat(auto-fill, 275px)",
      gridTemplateRows: "repeat(auto-fill, 125px)",
      gap: "15px",
      width: "100vw",
      margin: "8px",
    },
    communityList: {
      display: "flex",
      alignContent: "center",
      flexDirection: "column",
      gap: "10px",
      height: "550px",
      padding: "10px 22px",
      overflowY: "scroll",
      overflowX: "hidden",
      "&::-webkit-scrollbar": {
        display: "none",
      },
    },
    pictureBox: {
      display: "flex",
      height: "35px",
      margin: "5px",
      boxShadow: "0 5px 10px -5px rgba(0,0,0,0.5)",
      border: "2px solid white",
      borderRadius: "50%",
      aspectRatio: "1",
      overflow: "hidden",
      backgroundColor: "accent",
    },
  },
};
